#!/usr/bin/env bash
# scripts/setup-secrets.sh
# ─────────────────────────────────────────────────────────────────────────────
# Sets all required GitHub Actions secrets via the gh CLI.
# Run this once after setup-gcp.sh and setup-argocd.sh.
#
# Prerequisites:
#   - gh CLI authenticated: gh auth login
#   - GCP SA key file generated by setup-gcp.sh
#
# Usage:
#   export GITHUB_REPO=YOUR_ORG/gitops-pipeline
#   export GCP_PROJECT_ID=my-project-id
#   export SA_KEY_FILE=./sa-key-github-actions-cicd.json
#   export STAGING_URL=https://gitops-demo.staging.example.com
#   export PROD_URL=https://gitops-demo.example.com
#   ./scripts/setup-secrets.sh
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

GITHUB_REPO="${GITHUB_REPO:?Set GITHUB_REPO as ORG/REPO}"
GCP_PROJECT_ID="${GCP_PROJECT_ID:?Set GCP_PROJECT_ID}"
SA_KEY_FILE="${SA_KEY_FILE:?Set SA_KEY_FILE path to the service account JSON key}"
STAGING_URL="${STAGING_URL:-https://gitops-demo.staging.example.com}"
PROD_URL="${PROD_URL:-https://gitops-demo.example.com}"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
info()    { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }
section() { echo -e "\n${GREEN}━━━ $* ━━━${NC}"; }

# ── Preflight checks ──────────────────────────────────────────────────────────
section "Preflight checks"

command -v gh &>/dev/null  || error "gh CLI not installed. Install: https://cli.github.com"
gh auth status &>/dev/null || error "gh CLI not authenticated. Run: gh auth login"
[ -f "${SA_KEY_FILE}" ]    || error "SA key file not found: ${SA_KEY_FILE}"

info "All preflight checks passed."
info "Configuring secrets for: github.com/${GITHUB_REPO}"

# ── Helper: set a secret ──────────────────────────────────────────────────────
set_secret() {
  local NAME="$1"
  local VALUE="$2"
  echo -n "  Setting ${NAME}..."
  echo "${VALUE}" | gh secret set "${NAME}" --repo="${GITHUB_REPO}"
  echo -e " ${GREEN}✓${NC}"
}

set_secret_file() {
  local NAME="$1"
  local FILE="$2"
  echo -n "  Setting ${NAME} (from file)..."
  gh secret set "${NAME}" --repo="${GITHUB_REPO}" < "${FILE}"
  echo -e " ${GREEN}✓${NC}"
}

# ── GCP Secrets ───────────────────────────────────────────────────────────────
section "Setting GCP secrets"
set_secret_file "GCP_SA_KEY"    "${SA_KEY_FILE}"
set_secret       "GCP_PROJECT_ID" "${GCP_PROJECT_ID}"

# ── Application URLs ─────────────────────────────────────────────────────────
section "Setting application URL secrets"
set_secret "STAGING_URL" "${STAGING_URL}"
set_secret "PROD_URL"    "${PROD_URL}"

# ── GitHub Environment Protection (for prod manual approval) ─────────────────
section "Creating GitHub Environments"

# Create 'production' environment with required reviewers
cat <<EOF
Manual step required:
  1. Go to: https://github.com/${GITHUB_REPO}/settings/environments
  2. Create environment: "production"
  3. Add "Required reviewers": add your release-manager team
  4. Enable "Prevent self-review"
  5. (Optional) Restrict to 'release/*' branches
EOF

# ── Optional: ArgoCD notification webhook ────────────────────────────────────
section "Optional: Slack Webhook"
if [ -n "${SLACK_WEBHOOK_URL:-}" ]; then
  set_secret "SLACK_WEBHOOK_URL" "${SLACK_WEBHOOK_URL}"
  info "Slack webhook configured."
else
  warn "SLACK_WEBHOOK_URL not set — skipping Slack notifications."
  warn "Set it and re-run to enable deploy notifications."
fi

# ── Verify secrets ────────────────────────────────────────────────────────────
section "Verifying secrets"
echo ""
echo "Secrets registered in github.com/${GITHUB_REPO}:"
gh secret list --repo="${GITHUB_REPO}" | while IFS= read -r line; do
  echo "  ✓ ${line}"
done

# ── Cleanup warning ───────────────────────────────────────────────────────────
section "Cleanup"
warn "⚠️  Now delete the local SA key file:"
warn "    rm ${SA_KEY_FILE}"

section "GitHub Secrets Setup Complete"
echo ""
echo "  All secrets are now available to GitHub Actions workflows."
echo "  Push to the 'dev' branch to trigger your first pipeline!"
