# k8s/base/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: gitops-demo
  labels:
    app: gitops-demo
    managed-by: argocd
  annotations:
    # GCP: creates internal load balancer annotation (overrideable)
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app: gitops-demo
  ports:
    - name: http
      port: 80
      targetPort: http        # Named port in Deployment
      protocol: TCP
